/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-mipsel-openwrt"
#define DATE "built on: Fri Mar 22 22:09:42 2024 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','m','i','p','s','e','l',
    '-','o','p','e','n','w','r','t','-','l','i','n','u','x','-','m',
    'u','s','l','-','g','c','c',' ','-','f','P','I','C',' ','-','p',
    't','h','r','e','a','d',' ','-','m','a','b','i','=','3','2',' ',
    '-','W','a','l','l',' ','-','O','3',' ','-','O','s',' ','-','p',
    'i','p','e',' ','-','m','n','o','-','b','r','a','n','c','h','-',
    'l','i','k','e','l','y',' ','-','m','i','p','s','3','2','r','2',
    ' ','-','m','t','u','n','e','=','2','4','k','c',' ','-','f','n',
    'o','-','c','a','l','l','e','r','-','s','a','v','e','s',' ','-',
    'f','n','o','-','p','l','t',' ','-','f','h','o','n','o','u','r',
    '-','c','o','p','t','s',' ','-','m','s','o','f','t','-','f','l',
    'o','a','t',' ','-','f','f','u','n','c','t','i','o','n','-','s',
    'e','c','t','i','o','n','s',' ','-','f','d','a','t','a','-','s',
    'e','c','t','i','o','n','s',' ','-','W','f','o','r','m','a','t',
    ' ','-','W','e','r','r','o','r','=','f','o','r','m','a','t','-',
    's','e','c','u','r','i','t','y',' ','-','f','s','t','a','c','k',
    '-','p','r','o','t','e','c','t','o','r',' ','-','D','_','F','O',
    'R','T','I','F','Y','_','S','O','U','R','C','E','=','1',' ','-',
    'W','l',',','-','z',',','n','o','w',' ','-','W','l',',','-','z',
    ',','r','e','l','r','o',' ','-','D','P','I','C',' ','-','f','p',
    'i','c',' ','-','O','s',' ','-','p','i','p','e',' ','-','m','n',
    'o','-','b','r','a','n','c','h','-','l','i','k','e','l','y',' ',
    '-','m','i','p','s','3','2','r','2',' ','-','m','t','u','n','e',
    '=','2','4','k','c',' ','-','f','n','o','-','c','a','l','l','e',
    'r','-','s','a','v','e','s',' ','-','f','n','o','-','p','l','t',
    ' ','-','f','h','o','n','o','u','r','-','c','o','p','t','s',' ',
    '-','m','s','o','f','t','-','f','l','o','a','t',' ','-','f','f',
    'u','n','c','t','i','o','n','-','s','e','c','t','i','o','n','s',
    ' ','-','f','d','a','t','a','-','s','e','c','t','i','o','n','s',
    ' ','-','W','f','o','r','m','a','t',' ','-','W','e','r','r','o',
    'r','=','f','o','r','m','a','t','-','s','e','c','u','r','i','t',
    'y',' ','-','f','s','t','a','c','k','-','p','r','o','t','e','c',
    't','o','r',' ','-','f','p','i','c',' ','-','z','n','o','w',' ',
    '-','z','r','e','l','r','o',' ','-','D','O','P','E','N','S','S',
    'L','_','U','S','E','_','N','O','D','E','L','E','T','E',' ','-',
    'D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D','O',
    'P','E','N','S','S','L','_','B','U','I','L','D','I','N','G','_',
    'O','P','E','N','S','S','L',' ','-','D','N','D','E','B','U','G',
    ' ','-','D','_','F','O','R','T','I','F','Y','_','S','O','U','R',
    'C','E','=','1',' ','-','D','P','I','C','\0'
};
