/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/notlean/openwrt-uboost/staging_dir/host"
#define EXEC_PREFIX "/home/notlean/openwrt-uboost/staging_dir/host"
#define BINDIR "/home/notlean/openwrt-uboost/staging_dir/host/bin"
#define SBINDIR "/home/notlean/openwrt-uboost/staging_dir/host/bin"
#define LIBEXECDIR "/home/notlean/openwrt-uboost/staging_dir/host/libexec"
#define DATAROOTDIR "/home/notlean/openwrt-uboost/staging_dir/host/share"
#define DATADIR "/home/notlean/openwrt-uboost/staging_dir/host/share"
#define SYSCONFDIR "/home/notlean/openwrt-uboost/staging_dir/host/etc"
#define SHAREDSTATEDIR "/home/notlean/openwrt-uboost/staging_dir/host/com"
#define LOCALSTATEDIR "/home/notlean/openwrt-uboost/staging_dir/host/var"
#define RUNSTATEDIR "/home/notlean/openwrt-uboost/staging_dir/host/var/run"
#define INCLUDEDIR "/home/notlean/openwrt-uboost/staging_dir/host/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/notlean/openwrt-uboost/staging_dir/host/share/doc/m4"
#define INFODIR "/home/notlean/openwrt-uboost/staging_dir/host/share/info"
#define HTMLDIR "/home/notlean/openwrt-uboost/staging_dir/host/share/doc/m4"
#define DVIDIR "/home/notlean/openwrt-uboost/staging_dir/host/share/doc/m4"
#define PDFDIR "/home/notlean/openwrt-uboost/staging_dir/host/share/doc/m4"
#define PSDIR "/home/notlean/openwrt-uboost/staging_dir/host/share/doc/m4"
#define LIBDIR "/home/notlean/openwrt-uboost/staging_dir/host/lib"
#define LISPDIR "/home/notlean/openwrt-uboost/staging_dir/host/share/emacs/site-lisp"
#define LOCALEDIR "/home/notlean/openwrt-uboost/staging_dir/host/share/locale"
#define MANDIR "/home/notlean/openwrt-uboost/staging_dir/host/share/man"
#define PKGDATADIR "/home/notlean/openwrt-uboost/staging_dir/host/share/m4"
#define PKGINCLUDEDIR "/home/notlean/openwrt-uboost/staging_dir/host/include/m4"
#define PKGLIBDIR "/home/notlean/openwrt-uboost/staging_dir/host/lib/m4"
#define PKGLIBEXECDIR "/home/notlean/openwrt-uboost/staging_dir/host/libexec/m4"
